sudo: required
cache:
  directories:
    - '$HOME/.npm'
    - '$HOME/.cache'

services:
  - docker

jobs:
  include:
    - stage: testing
      script:
        - echo $TRAVIS_COMMIT_MESSAGE
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker-compose build
        - docker ps
deploy:
  provider: script
  script: docker-compose push
  on:
    branch: master
