sudo: required
cache:
  directories:
    - '$HOME/.npm'
    - '$HOME/.cache'

services:
  - docker

jobs:
  include:
    - stage: testing
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - git clone https://github.com/UniversityOfHelsinkiCS/oodikone2-cli.git
        - cd oodikone2-cli
        - source scripts.sh && run_e2e_setup
        - cd ..
        - until $(curl --output /dev/null --silent --fail http://localhost); do printf '.'; sleep 5; done
        - CYPRESS_baseUrl=http://localhost npm run cypress:record

