sudo: required
cache:
  directories:
    - '$HOME/.npm'
    - '$HOME/.cache'

services:
  - docker

jobs:
  include:
    - stage: testing
      script:
        - echo $TRAVIS_COMMIT_MESSAGE
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - git clone https://github.com/UniversityOfHelsinkiCS/oodikone.git
        - cd oodikone
        - source scripts.sh && run_e2e_setup
        - cd ..
        - docker ps 
        - cat oodikone/nginx/log
        - until $(curl --output /dev/null --silent --fail http://localhost:1337/staging/); do printf '.'; sleep 5; done
        - CYPRESS_baseUrl=http://localhost:1337/staging/ npm run cypress:record

deploy:
  provider: script
  script: ./src/release.sh ${TRAVIS_ACCESS_TOKEN} toska
  on:
    branch: master
